In [22]:
import pandas as pd

In [23]:
ruta_archivo = "raw/directorio_mineduc.csv"
df_colegios = pd.read_csv(ruta_archivo, sep=";")
print(df_colegios.shape)

(16768, 58)

In [24]:
pd.set_option("display.max_columns", None)
df_colegios.head()

,AGNO,RBD,DGV_RBD,NOM_RBD,MRUN,RUT_SOSTENEDOR,P_JURIDICA,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,NOM_DEPROV_RBD,COD_DEPE,COD_DEPE2,RURAL_RBD,LATITUD,LONGITUD,CONVENIO_PIE,PACE,ENS_01,ENS_02,ENS_03,ENS_04,ENS_05,ENS_06,ENS_07,ENS_08,ENS_09,ENS_10,ENS_11,MAT_ENS_1,MAT_ENS_2,MAT_ENS_3,MAT_ENS_4,MAT_ENS_5,MAT_ENS_6,MAT_ENS_7,MAT_ENS_8,MAT_TOTAL,MATRICULA,ESTADO_ESTAB,ORI_RELIGIOSA,ORI_OTRO_GLOSA,PAGO_MATRICULA,PAGO_MENSUAL,ESPE_01,ESPE_02,ESPE_03,ESPE_04,ESPE_05,ESPE_06,ESPE_07,ESPE_08,ESPE_09,ESPE_10,ESPE_11
0,2025,1,9,LICEO POLITECNICO ARICA,,62000660,1,15,AYP,151,15101,ARICA,151,ARICA,6,5,0,"-18,4872","-70,295212",1,1,463,510,563,610,663,0,0,0,0,0,0,0,0,0,0,0,0,862,224,1086,1,1,2,,GRATUITO,GRATUITO,41001,52009,52010,52013,53014,53015,61002,61003,62004,64001,0
1,2025,2,7,PARVULARIO LAS ESPIGUITAS,,62000660,1,15,AYP,151,15101,ARICA,151,ARICA,6,5,0,"-18,46986198","-70,30275726",1,0,10,0,0,0,0,0,0,0,0,0,0,112,0,0,0,0,0,0,0,112,1,1,1,,GRATUITO,GRATUITO,0,0,0,0,0,0,0,0,0,0,0
2,2025,3,5,ESC. PEDRO VICENTE GUTIERREZ TORRES,,62000660,1,15,AYP,151,15101,ARICA,151,ARICA,6,5,1,"-18,50358009","-70,26082611",0,0,165,167,363,0,0,0,0,0,0,0,0,0,0,491,0,0,6,0,0,497,1,1,1,,GRATUITO,GRATUITO,0,0,0,0,0,0,0,0,0,0,0
3,2025,4,3,LICEO OCTAVIO PALMA PEREZ,,62000660,1,15,AYP,151,15101,ARICA,151,ARICA,6,5,0,"-18,474239","-70,308273",1,1,310,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1279,0,0,0,1279,1,1,1,,GRATUITO,GRATUITO,0,0,0,0,0,0,0,0,0,0,0
4,2025,5,1,JOVINA NARANJO FERNANDEZ,,62000660,1,15,AYP,151,15101,ARICA,151,ARICA,6,5,0,"-18,4769","-70,313454",1,1,110,310,363,0,0,0,0,0,0,0,0,0,213,0,0,489,81,0,0,783,1,1,7,PLURALISTA,GRATUITO,GRATUITO,0,0,0,0,0,0,0,0,0,0,0

In [25]:
df_pudahuel = df_colegios[df_colegios["NOM_COM_RBD"] == "PUDAHUEL"]
print(f"Número de colegios encontrados en Pudahuel: {df_pudahuel.shape[0]}")

Número de colegios encontrados en Pudahuel: 85

In [26]:
print(df_pudahuel.columns.tolist())

['AGNO', 'RBD', 'DGV_RBD', 'NOM_RBD', 'MRUN', 'RUT_SOSTENEDOR', 'P_JURIDICA', 'COD_REG_RBD', 'NOM_REG_RBD_A', 'COD_PRO_RBD', 'COD_COM_RBD', 'NOM_COM_RBD', 'COD_DEPROV_RBD', 'NOM_DEPROV_RBD', 'COD_DEPE', 'COD_DEPE2', 'RURAL_RBD', 'LATITUD', 'LONGITUD', 'CONVENIO_PIE', 'PACE', 'ENS_01', 'ENS_02', 'ENS_03', 'ENS_04', 'ENS_05', 'ENS_06', 'ENS_07', 'ENS_08', 'ENS_09', 'ENS_10', 'ENS_11', 'MAT_ENS_1', 'MAT_ENS_2', 'MAT_ENS_3', 'MAT_ENS_4', 'MAT_ENS_5', 'MAT_ENS_6', 'MAT_ENS_7', 'MAT_ENS_8', 'MAT_TOTAL', 'MATRICULA', 'ESTADO_ESTAB', 'ORI_RELIGIOSA', 'ORI_OTRO_GLOSA', 'PAGO_MATRICULA', 'PAGO_MENSUAL', 'ESPE_01', 'ESPE_02', 'ESPE_03', 'ESPE_04', 'ESPE_05', 'ESPE_06', 'ESPE_07', 'ESPE_08', 'ESPE_09', 'ESPE_10', 'ESPE_11']

In [30]:
columnas_clave = [
'RBD',  
'NOM_RBD',  
'ESTADO_ESTAB', 
'NOM_COM_RBD', 
'ORI_RELIGIOSA', 
'ORI_OTRO_GLOSA', 
'PAGO_MATRICULA',
'PAGO_MENSUAL', 
'COD_DEPE',
'LATITUD', 
'LONGITUD', 
'RURAL_RBD', 
'MAT_TOTAL' 
]

df_edubig_base = df_pudahuel[columnas_clave]
df_edubig_base.head()

,RBD,NOM_RBD,ESTADO_ESTAB,NOM_COM_RBD,ORI_RELIGIOSA,ORI_OTRO_GLOSA,PAGO_MATRICULA,PAGO_MENSUAL,COD_DEPE,LATITUD,LONGITUD,RURAL_RBD,MAT_TOTAL
7999,9974,ESC. BASICA PART.SUBVENCIONADA LICAN-RAY,3,PUDAHUEL,9,,SIN INFORMACION,SIN INFORMACION,3,,,0,0
8063,10077,LICEO CENTRO EXPERIMENTAL PUDAHUEL CAREN,1,PUDAHUEL,7,LAICA,GRATUITO,GRATUITO,6,"-33,44455765","-70,75031812",0,431
8064,10078,ESCUELA MONSENOR MANUEL LARRAIN,3,PUDAHUEL,9,,SIN INFORMACION,SIN INFORMACION,6,,,0,0
8065,10080,ESCUELA TENIENTE HERNAN MERINO CORREA,1,PUDAHUEL,1,,GRATUITO,GRATUITO,6,"-33,43256326","-70,76105032",0,322
8066,10081,ESCUELA ESTRELLA DE CHILE,1,PUDAHUEL,1,,GRATUITO,GRATUITO,6,"-33,43659884","-70,74768617",0,973

In [32]:
import os

ruta_salida = "../web-app/public/data"
os.makedirs(ruta_salida, exist_ok=True)

df_edubig_base.to_json(f"{ruta_salida}/colegios_base.json", orient='records', force_ascii=False)