## 1. Importar librerías

In [1]:
import pandas as pd

denuncias_24 = pd.read_csv('../raw/20241231_DENUNCIAS_2024_20260331_PUBL.csv', sep=';', encoding='latin-1')

denuncias_25 = pd.read_csv('../raw/20251231_DENUNCIAS_2025_20260331_PUBL.csv', sep=';', encoding='latin-1')

idps_2m_25 = pd.read_csv('../raw/idps2M2025_rbd_preliminar.csv', sep=';', encoding='latin-1')

idps_4b_25 = pd.read_csv('../raw/idps4B2025_rbd_preliminar.csv', sep=';', encoding='latin-1')

idps_8b_25 = pd.read_csv('../raw/idps8B2025_rbd_preliminar.csv', sep=';', encoding='latin-1')

simce_2m_25 = pd.read_csv('../raw/simce2m2025_rbd_preliminar.csv', sep=';', encoding='latin-1')

simce_4b_25 = pd.read_csv('../raw/simce4b2025_rbd_preliminar.csv', sep=';', encoding='latin-1')

simce_6b_24 = pd.read_csv('../raw/simce6b2024_rbd_final.csv', sep=';', encoding='latin-1')

simce_8b_25 = pd.read_csv('../raw/simce8b2025_rbd_preliminar.csv', sep=';', encoding='latin-1')

colegios_base = pd.read_json('../../web-app/public/data/colegios_base.json')

In [2]:
print('denuncias_24: ', denuncias_24.shape)
print('denuncias_25: ', denuncias_25.shape)
print('idps_2m_25: ', idps_2m_25.shape)
print('idps_4b_25: ', idps_4b_25.shape)
print('idps_8b_25: ', idps_8b_25.shape)
print('simce_2m_25: ', simce_2m_25.shape)
print('simce_4b_25: ', simce_4b_25.shape)
print('simce_6b_24: ', simce_6b_24.shape)
print('simce_8b_25: ', simce_8b_25.shape)
print('colegios_base: ', colegios_base.shape)

denuncias_24:  (19114, 42)
denuncias_25:  (22519, 42)
idps_2m_25:  (11996, 24)
idps_4b_25:  (26868, 24)
idps_8b_25:  (23844, 24)
simce_2m_25:  (3002, 42)
simce_4b_25:  (7143, 42)
simce_6b_24:  (7086, 42)
simce_8b_25:  (6026, 50)
colegios_base:  (85, 13)

2.Limpieza de datos / denuncias

In [3]:
denuncias_24.columns.tolist()

['ï»¿AGNO',
 'DEN_ID',
 'DEN_CANAL',
 'DEN_ESTADO',
 'DEN_FEC_CREACION',
 'DEN_MES_CREACION',
 'DEN_TRIMESTRE_CREACION',
 'DEN_FEC_TERMINO_DENUNCIA',
 'DEN_OFICINA',
 'DEN_DEPARTAMENTO',
 'DEN_AMBITO',
 'DEN_TEMA',
 'DEN_SUBTEMA',
 'DEN_ENVIO_RESP',
 'FIS_ID',
 'FIS_ID_SEGUIMIENTO',
 'PA_ID',
 'DEN_MRUN',
 'DEN_AFECTADO',
 'DEN_GENERO',
 'DEN_SEXO',
 'DEN_TIPO',
 'AFEC_MRUN',
 'AFEC_GENERO',
 'AFEC_SEXO',
 'AFEC_TIPO',
 'RBD',
 'RSIE',
 'EE_NOMBRE',
 'EE_COD_REGION',
 'EE_COD_PROVINCIA',
 'EE_COD_COMUNA',
 'EE_NOM_COMUNA',
 'EE_COD_DEPE',
 'EE_COD_DEPE_AGRUP',
 'AFEC_COD_ENSE2',
 'DEN_TIPO_INSTITUCION',
 'SOST_RUT',
 'SOST_MRUN',
 'SOST_NOMBRE',
 'DEN_REGION',
 'DEN_CIBERBULLYING']

In [4]:
denuncias_24 = denuncias_24.rename(columns={'ï»¿AGNO': 'agno', 'RBD': 'rbd'})

In [5]:
denuncias_25.columns.tolist()

['ï»¿AGNO',
 'DEN_ID',
 'DEN_CANAL',
 'DEN_ESTADO',
 'DEN_FEC_CREACION',
 'DEN_MES_CREACION',
 'DEN_TRIMESTRE_CREACION',
 'DEN_FEC_TERMINO_DENUNCIA',
 'DEN_OFICINA',
 'DEN_DEPARTAMENTO',
 'DEN_AMBITO',
 'DEN_TEMA',
 'DEN_SUBTEMA',
 'DEN_ENVIO_RESP',
 'FIS_ID',
 'FIS_ID_SEGUIMIENTO',
 'PA_ID',
 'DEN_MRUN',
 'DEN_AFECTADO',
 'DEN_GENERO',
 'DEN_SEXO',
 'DEN_TIPO',
 'AFEC_MRUN',
 'AFEC_GENERO',
 'AFEC_SEXO',
 'AFEC_TIPO',
 'RBD',
 'RSIE',
 'EE_NOMBRE',
 'EE_COD_REGION',
 'EE_COD_PROVINCIA',
 'EE_COD_COMUNA',
 'EE_NOM_COMUNA',
 'EE_COD_DEPE',
 'EE_COD_DEPE_AGRUP',
 'AFEC_COD_ENSE2',
 'DEN_TIPO_INSTITUCION',
 'SOST_RUT',
 'SOST_MRUN',
 'SOST_NOMBRE',
 'DEN_REGION',
 'DEN_CIBERBULLYING']

In [6]:
denuncias_25 = denuncias_25.rename(columns={'ï»¿AGNO': 'agno', 'RBD': 'rbd'})

In [7]:
denuncias_25_limpia = denuncias_25[['agno', 'rbd']]

denuncias_24_limpia = denuncias_24[['agno', 'rbd']]

In [8]:
denuncias_24_limpia = denuncias_24_limpia[denuncias_24_limpia['rbd'].str.strip() != '']

denuncias_24_limpia['rbd'] = denuncias_24_limpia['rbd'].str.strip().astype('int64')

denuncias_25_limpia = denuncias_25_limpia[denuncias_25_limpia['rbd'].str.strip() != '']

denuncias_25_limpia['rbd'] = denuncias_25_limpia['rbd'].str.strip().astype('int64')

In [9]:
denuncias_agrupadas_25 = denuncias_25_limpia.groupby('rbd').size().reset_index(name='conteo_denuncias_25')

denuncias_agrupadas_24 = denuncias_24_limpia.groupby('rbd').size().reset_index(name='conteo_denuncias_24')

In [10]:
print(denuncias_agrupadas_24.shape)
print(denuncias_agrupadas_25.shape)

(5676, 2)
(5873, 2)

2.1 Limpieza de datos / idps

In [11]:
idps_2m_25.head()

,rbd,agno,id_indicador,prom,dif,mdif,sigdif,difgru,mdifgru,sigdifgru,...,nom_pro_rbd,cod_com_rbd,nom_com_rbd,nom_deprov_rbd,cod_depe2,cod_grupo,cod_rural_rbd,codigo_bbdd,fecha_bbdd,grado
0,1,2025,1,70.0,-4.0,NaN,0.0,-4.0,NaN,0.0,...,ARICA,15101,ARICA,Arica,4,1,1,v12025,20260423,2m
1,1,2025,2,70.0,-5.0,NaN,-1.0,-5.0,NaN,-1.0,...,ARICA,15101,ARICA,Arica,4,1,1,v12025,20260423,2m
2,1,2025,3,73.0,-6.0,NaN,-1.0,-4.0,NaN,0.0,...,ARICA,15101,ARICA,Arica,4,1,1,v12025,20260423,2m
3,1,2025,4,71.0,-3.0,NaN,0.0,-1.0,NaN,0.0,...,ARICA,15101,ARICA,Arica,4,1,1,v12025,20260423,2m
4,4,2025,1,74.0,0.0,NaN,0.0,1.0,NaN,0.0,...,ARICA,15101,ARICA,Arica,4,3,1,v12025,20260423,2m

In [12]:
idps_2m_25_limpia = idps_2m_25[['rbd', 'id_indicador', 'prom', 'dif', 'difgru', 'sigdifgru']]

idps_4b_25_limpia = idps_4b_25[['rbd', 'id_indicador', 'prom', 'dif', 'difgru', 'sigdifgru']]

idps_8b_25_limpia = idps_8b_25[['rbd', 'id_indicador', 'prom', 'dif', 'difgru', 'sigdifgru']]

In [13]:
idps_2m_25_pivot = idps_2m_25_limpia.pivot_table(index='rbd', columns='id_indicador', values=['prom', 'dif', 'difgru', 'sigdifgru'], aggfunc= 'mean').reset_index()

idps_2m_25_pivot.head()

             rbd  dif                difgru                 prom              \
id_indicador        1    2    3    4      1    2    3    4     1     2     3
0              1 -4.0 -5.0 -6.0 -3.0   -4.0 -5.0 -4.0 -1.0  70.0  70.0  73.0
1              4  0.0  1.0  1.0 -2.0    1.0  0.0  0.0 -1.0  74.0  75.0  76.0
2              5  1.0  0.0  2.0  0.0   -1.0 -2.0  1.0  2.0  72.0  73.0  77.0
3              7  0.0  3.0  2.0  0.0   -2.0  1.0 -1.0  0.0  72.0  76.0  76.0
4              8  NaN  NaN  NaN  NaN    1.0  2.0  2.0  2.0  75.0  77.0  78.0

                   sigdifgru
id_indicador     4         1    2    3    4
0             71.0       0.0 -1.0  0.0  0.0
1             68.0       0.0  0.0  0.0  0.0
2             71.0       0.0  0.0  0.0  0.0
3             72.0       0.0  0.0  0.0  0.0
4             73.0       0.0  0.0  0.0  0.0

In [14]:
idps_2m_25_pivot.columns =['rbd', 
'autoestima_dif_2m', 'clima_dif_2m', 'participacion_dif_2m', 'habitos_dif_2m', 
'autoestima_difgru_2m', 'clima_difgru_2m', 'participacion_difgru_2m', 'habitos_difgru_2m', 
'autoestima_prom_2m', 'clima_prom_2m', 'participacion_prom_2m', 'habitos_prom_2m', 
'autoestima_sigdifgru_2m', 'clima_sigdifgru_2m', 'participacion_sigdifgru_2m', 'habitos_sigdifgru_2m'
]

idps_2m_25_pivot.shape

(2998, 17)

In [15]:
idps_4b_25_pivot = idps_4b_25_limpia.pivot_table(index='rbd', columns='id_indicador', values=['prom', 'dif', 'difgru', 'sigdifgru'], aggfunc= 'mean').reset_index()

idps_8b_25_pivot = idps_8b_25_limpia.pivot_table(index='rbd', columns='id_indicador', values=['prom', 'dif', 'difgru', 'sigdifgru'], aggfunc= 'mean').reset_index()

In [16]:
idps_4b_25_pivot.columns = ['rbd', 
'autoestima_dif_4b', 'clima_dif_4b', 'participacion_dif_4b', 'habitos_dif_4b', 
'autoestima_difgru_4b', 'clima_difgru_4b', 'participacion_difgru_4b', 'habitos_difgru_4b', 
'autoestima_prom_4b', 'clima_prom_4b', 'participacion_prom_4b', 'habitos_prom_4b', 
'autoestima_sigdifgru_4b', 'clima_sigdifgru_4b', 'participacion_sigdifgru_4b', 'habitos_sigdifgru_4b'
]

idps_8b_25_pivot.columns = ['rbd', 
'autoestima_dif_8b', 'clima_dif_8b', 'participacion_dif_8b', 'habitos_dif_8b', 
'autoestima_difgru_8b', 'clima_difgru_8b', 'participacion_difgru_8b', 'habitos_difgru_8b', 
'autoestima_prom_8b', 'clima_prom_8b', 'participacion_prom_8b', 'habitos_prom_8b', 
'autoestima_sigdifgru_8b', 'clima_sigdifgru_8b', 'participacion_sigdifgru_8b', 'habitos_sigdifgru_8b'
]

print(idps_8b_25_pivot.shape)
print(idps_4b_25_pivot.shape)

(5936, 17)
(6633, 17)

2.2 Limpieza de datos / simce

In [17]:
simce_2m_25_limpia = simce_2m_25[['rbd', 'cod_grupo', 'prom_lect2m_rbd', 'prom_mate2m_rbd',
                                    'difgru_lect2m_rbd', 'difgru_mate2m_rbd',
                                    'siggru_lect2m_rbd', 'siggru_mate2m_rbd']]

simce_4b_25_limpia = simce_4b_25[['rbd', 'cod_grupo', 'prom_lect4b_rbd', 'prom_mate4b_rbd',
                                    'difgru_lect4b_rbd', 'difgru_mate4b_rbd',
                                    'siggru_lect4b_rbd', 'siggru_mate4b_rbd']]

simce_6b_24_limpia = simce_6b_24[['rbd', 'cod_grupo', 'prom_lect6b_rbd', 'prom_mate6b_rbd',
                                    'difgru_lect6b_rbd', 'difgru_mate6b_rbd',
                                    'siggru_lect6b_rbd', 'siggru_mate6b_rbd']]

simce_8b_25_limpia = simce_8b_25[['rbd', 'cod_grupo', 'prom_lect8b_rbd', 'prom_mate8b_rbd', 'prom_hist8b_rbd',
                                    'difgru_lect8b_rbd', 'difgru_mate8b_rbd', 'difgru_hist8b_rbd',
                                    'siggru_lect8b_rbd', 'siggru_mate8b_rbd', 'siggru_hist8b_rbd']]

In [18]:
simce_2m_25_limpia = simce_2m_25_limpia.rename(columns={'cod_grupo': 'cod_grupo_2m'})

simce_4b_25_limpia = simce_4b_25_limpia.rename(columns={'cod_grupo': 'cod_grupo_4b'})

simce_6b_24_limpia = simce_6b_24_limpia.rename(columns={'cod_grupo': 'cod_grupo_6b'})

simce_8b_25_limpia = simce_8b_25_limpia.rename(columns={'cod_grupo': 'cod_grupo_8b'})

In [19]:
simce_8b_25_limpia.head()

,rbd,cod_grupo_8b,prom_lect8b_rbd,prom_mate8b_rbd,prom_hist8b_rbd,difgru_lect8b_rbd,difgru_mate8b_rbd,difgru_hist8b_rbd,siggru_lect8b_rbd,siggru_mate8b_rbd,siggru_hist8b_rbd
0,7826,3.0,235.0,259.0,245.0,-2.0,3.0,-3.0,0.0,0.0,0.0
1,10743,2.0,237.0,247.0,249.0,12.0,5.0,13.0,1.0,0.0,1.0
2,14324,5.0,260.0,283.0,279.0,-14.0,-22.0,-10.0,0.0,-1.0,0.0
3,2917,2.0,254.0,275.0,250.0,29.0,33.0,14.0,1.0,1.0,1.0
4,8513,4.0,218.0,238.0,232.0,-32.0,-35.0,-30.0,-1.0,-1.0,-1.0

2.3 Limpieza de datos / colegios_base

In [20]:
colegios_base.columns.tolist()

['RBD',
 'NOM_RBD',
 'ESTADO_ESTAB',
 'NOM_COM_RBD',
 'ORI_RELIGIOSA',
 'ORI_OTRO_GLOSA',
 'PAGO_MATRICULA',
 'PAGO_MENSUAL',
 'COD_DEPE',
 'LATITUD',
 'LONGITUD',
 'RURAL_RBD',
 'MAT_TOTAL']

In [21]:
colegios_base_limpio = colegios_base.rename(columns={'RBD': 'rbd'})

In [22]:
colegios_base_limpio.columns.tolist()

['rbd',
 'NOM_RBD',
 'ESTADO_ESTAB',
 'NOM_COM_RBD',
 'ORI_RELIGIOSA',
 'ORI_OTRO_GLOSA',
 'PAGO_MATRICULA',
 'PAGO_MENSUAL',
 'COD_DEPE',
 'LATITUD',
 'LONGITUD',
 'RURAL_RBD',
 'MAT_TOTAL']

In [23]:
colegios_base_limpio['LATITUD'] = colegios_base_limpio['LATITUD'].str.replace(',', '.')
colegios_base_limpio['LATITUD'] = pd.to_numeric(colegios_base_limpio['LATITUD'], errors='coerce')

colegios_base_limpio['LONGITUD'] = colegios_base_limpio['LONGITUD'].str.replace(',', '.')
colegios_base_limpio['LONGITUD'] = pd.to_numeric(colegios_base_limpio['LONGITUD'], errors='coerce')

In [24]:
print(colegios_base_limpio['LATITUD'])
print(colegios_base_limpio['LONGITUD'])

0           NaN
1    -33.444558
2           NaN
3    -33.432563
4    -33.436599
        ...
80   -33.462652
81   -33.454942
82   -33.378782
83          NaN
84   -33.431919
Name: LATITUD, Length: 85, dtype: float64
0           NaN
1    -70.750318
2           NaN
3    -70.761050
4    -70.747686
        ...
80   -70.856499
81   -70.765243
82   -70.798460
83          NaN
84   -70.764001
Name: LONGITUD, Length: 85, dtype: float64

3. Merge de los datos (utilizando 'rbd' como unificador)

In [25]:
colegios_enriquecidos = (colegios_base_limpio
.merge(simce_2m_25_limpia, on='rbd', how='left')
.merge(simce_4b_25_limpia, on='rbd', how='left')
.merge(simce_6b_24_limpia, on='rbd', how='left')
.merge(simce_8b_25_limpia, on='rbd', how='left')
.merge(denuncias_agrupadas_24, on='rbd', how='left')
.merge(denuncias_agrupadas_25, on='rbd', how='left')
.merge(idps_2m_25_pivot, on='rbd', how='left')
.merge(idps_4b_25_pivot, on='rbd', how='left')
.merge(idps_8b_25_pivot, on='rbd', how='left')
)

In [26]:
colegios_enriquecidos.shape

(85, 94)

In [27]:
colegios_enriquecidos.to_json("../../web-app/public/data/colegios_enriquecidos.json", orient='records')